import {
  Trip,
  EmergencyContact,
  TravelDocument,
  HotelProfile,
  TourismEvent,
  SafetyAlert,
  Incident,
  TripFeedback,
} from '../types';

export const INITIAL_EMBASSIES = [
  { country: 'United States', embassyName: 'U.S. Embassy New Delhi', phone: '+91 11 2419 8000', email: 'acsnz@state.gov', address: 'Shantipath, Chanakyapuri, New Delhi - 110021' },
  { country: 'United Kingdom', embassyName: 'British High Commission', phone: '+91 11 2419 2100', email: 'delhi.consular@fcdo.gov.uk', address: 'Shantipath, Chanakyapuri, New Delhi - 110021' },
  { country: 'Germany', embassyName: 'German Embassy New Delhi', phone: '+91 11 4419 9199', email: 'info@new-delhi.diplo.de', address: '6/50G Shantipath, Chanakyapuri, New Delhi - 110021' },
  { country: 'France', embassyName: 'Embassy of France in India', phone: '+91 11 4319 6100', email: 'admin-francais.new-delhi-amba@diplomatie.gouv.fr', address: '2/50-E Shantipath, Chanakyapuri, New Delhi' },
  { country: 'Japan', embassyName: 'Embassy of Japan in India', phone: '+91 11 4610 4610', email: 'jpembjic@nd.mofa.go.jp', address: '50-G Shantipath, Chanakyapuri, New Delhi - 110021' },
  { country: 'Australia', embassyName: 'Australian High Commission', phone: '+91 11 4139 9900', email: 'ahc.newdelhi@dfat.gov.au', address: '1/50G Shantipath, Chanakyapuri, New Delhi - 110021' },
];

export const INITIAL_TRIPS: Trip[] = [
  {
    id: 'trip-current-01',
    touristId: 'test-tourist-national-01',
    title: 'Heritage & Cultural Festival Pilgrimage',
    destinations: ['Grand Heritage Plaza', 'Keshava Temple Precinct', 'Riverwalk Ghats'],
    startDate: new Date(Date.now() - 36 * 3600 * 1000).toISOString(),
    endDate: new Date(Date.now() + 24 * 3600 * 1000).toISOString(), // Exactly 24h away for automation test!
    accommodationName: 'Grand Heritage Hotel',
    accommodationAddress: '12 Palace Boulevard, Central Zone',
    accommodationVerified: true,
    hotelId: 'hotel-01',
    status: 'ACTIVE',
    riskLevel: 'LOW',
    activities: ['Temple Morning Darshan', 'Cultural Dance Gala', 'Evening River Aarti'],
    travelMode: 'Registered Electric Shuttle',
    createdAt: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
  },
  {
    id: 'trip-intl-02',
    touristId: 'test-tourist-intl-02',
    title: 'Golden Triangle & Southern Temples Tour',
    destinations: ['Mysore Palace Grounds', 'Chamundi Hills Sanctuary'],
    startDate: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    endDate: new Date(Date.now() + 72 * 3600 * 1000).toISOString(),
    accommodationName: 'Royal Palace Suites',
    accommodationAddress: '45 Heritage Way, West Gate',
    accommodationVerified: true,
    hotelId: 'hotel-02',
    status: 'ACTIVE',
    riskLevel: 'LOW',
    activities: ['Palace Light Show', 'Silk & Sandalwood Market'],
    travelMode: 'Pre-paid Tourist Taxi',
    createdAt: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
  },
];

export const INITIAL_EMERGENCY_CONTACTS: EmergencyContact[] = [
  {
    id: 'contact-01',
    userId: 'test-tourist-national-01',
    name: 'Amina Mohammed',
    relationship: 'Sister / Next of Kin',
    phone: '+91 98450 11223',
    email: 'amina.m@family.org',
    priority: 'PRIMARY',
    verified: true,
    createdAt: '2026-08-01T10:00:00Z',
  },
  {
    id: 'contact-02',
    userId: 'test-tourist-national-01',
    name: 'Dr. Tariq Mohammed',
    relationship: 'Father / Guardian',
    phone: '+91 94480 33445',
    priority: 'SECONDARY',
    verified: true,
    createdAt: '2026-08-01T10:00:00Z',
  },
  {
    id: 'contact-03',
    userId: 'test-tourist-intl-02',
    name: 'Dmitri Rostova',
    relationship: 'Brother',
    phone: '+44 7700 900112',
    email: 'dmitri@travelsafe.co.uk',
    priority: 'PRIMARY',
    verified: true,
    createdAt: '2026-08-05T12:00:00Z',
  },
];

export const INITIAL_DOCUMENTS: TravelDocument[] = [
  {
    id: 'doc-01',
    userId: 'test-tourist-national-01',
    type: 'NATIONAL_ID',
    fileName: 'Aadhaar_Masked_Front.pdf',
    fileSize: 420000,
    verificationStatus: 'VERIFIED',
    verificationSource: 'Internal Review / Gov Gateway Sandbox',
    verificationTimestamp: '2026-08-02T14:30:00Z',
    maskedIdNumber: 'XXXX-XXXX-8912',
    createdAt: '2026-08-02T14:20:00Z',
  },
  {
    id: 'doc-02',
    userId: 'test-tourist-intl-02',
    type: 'PASSPORT',
    fileName: 'Passport_Bio_Page.jpg',
    fileSize: 1250000,
    verificationStatus: 'MANUAL_REVIEW',
    verificationSource: 'National Travel & Passport Gateway (Authorization Pending)',
    expiryDate: '2031-10-15',
    maskedIdNumber: 'GB-P****894',
    createdAt: '2026-08-05T12:30:00Z',
  },
  {
    id: 'doc-03',
    userId: 'test-tourist-intl-02',
    type: 'VISA',
    fileName: 'eVisa_Permit_India.pdf',
    fileSize: 680000,
    verificationStatus: 'VERIFIED',
    verificationSource: 'Consular Electronic Tourist Visa Portal',
    expiryDate: '2026-11-30',
    maskedIdNumber: 'IN-V****201',
    createdAt: '2026-08-05T12:35:00Z',
  },
];

export const INITIAL_HOTELS: HotelProfile[] = [
  {
    id: 'hotel-01',
    name: 'Grand Heritage Hotel & Convention',
    address: '12 Palace Boulevard, Central Zone, Karnataka',
    contactPhone: '+91 80 2345 6789',
    licenseNumber: 'KAR-HOTEL-REG-2024-8841',
    capacity: 250,
    verificationStatus: 'VERIFIED',
    verificationSource: 'State Department of Tourism License Board',
    verificationDate: '2026-01-15',
    safetyFacilities: ['24/7 Monitored CCTV', 'First Aid Station & Defibrillator', 'Fire Evacuation Plan', 'Direct Police Link'],
    managerUserId: 'test-hotel-07',
    rating: 4.8,
    createdAt: '2026-07-18T14:00:00Z',
  },
  {
    id: 'hotel-02',
    name: 'Royal Palace Suites & Ayurvedic Spa',
    address: '45 Heritage Way, West Gate Sector 4',
    contactPhone: '+91 80 4455 6677',
    licenseNumber: 'KAR-HOTEL-REG-2025-1092',
    capacity: 180,
    verificationStatus: 'VERIFIED',
    verificationSource: 'Tourism Municipal Board',
    verificationDate: '2026-02-10',
    safetyFacilities: ['Licensed Security Guards', 'Medical Oxygen Onsite', 'Multilingual Concierge'],
    managerUserId: 'test-hotel-07',
    rating: 4.6,
    createdAt: '2026-07-20T10:00:00Z',
  },
  {
    id: 'hotel-03',
    name: 'Riverside Eco Stay & Backpackers Inn',
    address: '8 Ghat View Lane, East Riverside',
    contactPhone: '+91 80 8899 0011',
    licenseNumber: 'PENDING-REG-2026-3391',
    capacity: 80,
    verificationStatus: 'UNDER_REVIEW',
    verificationSource: 'Inspection Scheduled by Tourism Authority',
    safetyFacilities: ['Smoke Detectors', 'Life Jackets for Ghat Access'],
    managerUserId: 'user-unverified-09',
    rating: 4.2,
    createdAt: '2026-08-10T11:00:00Z',
  },
];

export const INITIAL_EVENTS: TourismEvent[] = [
  {
    id: 'event-01',
    organizerId: 'test-organizer-04',
    name: 'Grand Dasara & Cultural Heritage Mahotsav 2026',
    description: 'Premier national tourism and cultural celebration featuring temple processions, illumination arts, and folk dance performances.',
    location: 'Palace Grounds & Temple Promenade',
    startDate: '2026-08-20T00:00:00Z',
    endDate: '2026-08-30T23:59:59Z',
    totalCapacity: 50000,
    status: 'ACTIVE',
    createdAt: '2026-07-20T11:30:00Z',
    zones: [
      {
        id: 'zone-a',
        eventId: 'event-01',
        name: 'Zone A - Main Palace Courtyard',
        capacity: 12000,
        currentCount: 5400,
        entryFlow: 120, // visitors/min
        exitFlow: 110,
        status: 'GREEN',
        densityRatio: 0.45,
        lastUpdated: new Date().toISOString(),
      },
      {
        id: 'zone-b',
        eventId: 'event-01',
        name: 'Zone B - East Gate & Promenade',
        capacity: 15000,
        currentCount: 8900,
        entryFlow: 240,
        exitFlow: 190,
        status: 'YELLOW',
        densityRatio: 0.59,
        lastUpdated: new Date().toISOString(),
      },
      {
        id: 'zone-c',
        eventId: 'event-01',
        name: 'Zone C - North Temple Ghat & Food Street',
        capacity: 8000,
        currentCount: 6600,
        entryFlow: 380,
        exitFlow: 140,
        status: 'ORANGE',
        densityRatio: 0.825,
        lastUpdated: new Date().toISOString(),
      },
      {
        id: 'zone-d',
        eventId: 'event-01',
        name: 'Zone D - West Handicrafts Pavilion',
        capacity: 10000,
        currentCount: 2200,
        entryFlow: 80,
        exitFlow: 90,
        status: 'GREEN',
        densityRatio: 0.22,
        lastUpdated: new Date().toISOString(),
      },
    ],
  },
];

export const INITIAL_ALERTS: SafetyAlert[] = [
  {
    id: 'alert-01',
    title: 'High Crowd Advisory - North Temple Ghat (Zone C)',
    description: 'Zone C density reached 82%. Tourist flow is being diverted towards West Handicrafts Pavilion (Gate D). Please follow directional signage.',
    type: 'CROWD',
    severity: 'HIGH',
    location: 'Zone C North Ghat Sector',
    radiusKm: 1.5,
    source: 'Festival Safety Command & Tourist Police',
    authorRole: 'TOURISM_AUTHORITY',
    status: 'ACTIVE',
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 3 * 3600 * 1000).toISOString(),
  },
  {
    id: 'alert-02',
    title: 'Evening Weather Notice - Light Thunder Showers',
    description: 'Moderate thunder showers expected between 18:30 - 20:00. Electric shuttle services remain active across all color-coded safe stops.',
    type: 'WEATHER',
    severity: 'MODERATE',
    location: 'Greater Festival District',
    radiusKm: 10,
    source: 'State Meteorological Centre',
    authorRole: 'ADMIN',
    status: 'ACTIVE',
    createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 6 * 3600 * 1000).toISOString(),
  },
  {
    id: 'alert-03',
    title: 'Safer Route Activated: East Bypass via Garden Link',
    description: 'Main arterial road undergoing pedestrian-only zoning. Shuttles redirected via Garden Link Avenue for optimal safety.',
    type: 'ROAD',
    severity: 'LOW',
    location: 'East Promenade Junction',
    radiusKm: 3,
    source: 'Traffic & Crowd Management Wing',
    authorRole: 'SECURITY_POLICE',
    status: 'ACTIVE',
    createdAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
  },
];

export const INITIAL_INCIDENTS: Incident[] = [
  {
    id: 'INC-8892',
    touristId: 'test-tourist-national-01',
    touristName: 'Fayaz Mohammed',
    touristPhone: '+91 98765 43210',
    touristType: 'NATIONAL',
    type: 'CROWD',
    severity: 'MODERATE',
    location: {
      latitude: 12.9716,
      longitude: 77.5946,
      address: 'Near Temple Gate B, Central Plaza',
      zoneName: 'Zone B - East Gate',
    },
    locationDescription: 'Temple Gate B East Promenade',
    description: 'Tourist reported excessive bottlenecking near Gate B security scanners.',
    consentState: {
      locationShared: true,
      emergencyDataShared: true,
    },
    assignedTeam: 'Tourist Police Quick Response Alpha',
    assignedResponderName: 'Inspector V. Kumar',
    status: 'ACKNOWLEDGED',
    escalationLevel: 1,
    externalDispatchStatus: 'NOT_CONNECTED_IN_DEV',
    actions: [
      {
        id: 'act-01',
        timestamp: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
        actorId: 'test-tourist-national-01',
        actorName: 'Fayaz Mohammed',
        actorRole: 'TOURIST_NATIONAL',
        action: 'INCIDENT_REPORTED',
        notes: 'Submitted via in-app crowd safety report tool.',
      },
      {
        id: 'act-02',
        timestamp: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
        actorId: 'test-police-05',
        actorName: 'Inspector V. Kumar',
        actorRole: 'SECURITY_POLICE',
        action: 'ACKNOWLEDGED_BY_SECURITY',
        notes: 'Dispatched 2 marshals to regulate entrance queue at Gate B.',
      },
    ],
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_FEEDBACK: TripFeedback[] = [
  {
    id: 'fb-01',
    tripId: 'trip-past-001',
    touristId: 'test-tourist-national-01',
    touristName: 'Fayaz Mohammed',
    overallRating: 5,
    safetyRating: 5,
    cleanlinessRating: 4,
    crowdingRating: 4,
    transportRating: 5,
    accommodationRating: 5,
    accessibilityRating: 4,
    comment: 'The real-time crowd diversion saved our family 45 minutes of wait time at the temple gates. Medical aid post was very clean and accessible.',
    consentLevel: 'PUBLIC_HIGHLIGHT',
    moderationStatus: 'APPROVED',
    createdAt: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
  },
];
